### ISSUE TITLE
"Bad Transformation Request" when using Transformation in URL generation

### ISSUE THREAD

**Issue by gabriellangon** [imagekit-developer/imagekit-php#61]
Hi,

I'm facing a "Bad URL Transformation Request" error when using transformations (such as height, width, or overlay image) in the URL generation function.

Even the example in the documentation at https://docs.imagekit.io/getting-started/quickstart-guides/php#5.-adding-overlays-to-images is returning the same error

$imageURL = $imageKit->url(
    [
        'path' => '/default-image.jpg', 
        'transformation' => [
            [
                'height' => '300',
                'width' => '300',
                'overlayImage' => 'default-image.jpg',
                'overlaywidth' => '100',
            ]
        ]
    ]
);

**Comment by wujekbogdan** [comment]
I'm having the same issue; it seems to be related to recent changes in the API. Instead of using watermarks, the new Layers API should be used: [https://docs.imagekit.io/features/image-transformations/overlay-using-layers](https://docs.imagekit.io/features/image-transformations/overlay-using-layers).

**Comment by imagekitio** [comment]
We have updated the examples in `master` branch readme.md. Please check https://github.com/imagekit-developer/imagekit-php?tab=readme-ov-file#5-adding-overlays
